name: proequine
description: ProEquine Mobile Application.


publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  video_player: ^2.4.7
  intl: ^0.17.0
  http: ^0.13.5
  flutter_dash: ^1.0.0
  dio: ^4.0.0
  flutter_bloc: ^8.0.1
  sizer: ^2.0.15
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.0
  flutter_svg: ^1.1.1+1
  logger: ^1.1.0
  fluttertoast: ^8.0.9
  image_stack: ^2.1.1
  dartz: ^0.10.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  rebi_tools: ^0.0.3
  carousel_slider: ^4.2.1
  url_launcher: ^6.0.10
  image_picker: ^0.8.5+3
  awesome_dialog: ^3.0.2
  webview_flutter: ^3.0.4
  jwt_decode: ^0.3.1
  pinput: ^2.2.31
  pull_to_refresh: ^2.0.0
  grouped_list: ^5.1.2
  auto_size_text:
  country_code_picker: ^3.0.0

  #firebase
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^13.0.2
  firebase_core: ^1.3.0

dev_dependencies:
  firebase_core_platform_interface: 4.5.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/


  # To add custom fonts to your application:
  fonts:
    - family: notosan
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyIcons.ttf
    - family: hemiHead
      fonts:
        - asset: assets/fonts/HemiHeadRg-BoldItalic 400.ttf

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
